const foodData = [
    {
        "id": "9",
        "name": "Bruschetta",
        "description": "Sliced toasted bread rubbed with garlic, topped with finely chopped onions and tomatoes and finished with a drizzle of high quality olive oil",
        "src": "bruschetta.jpg",
        "type": "Fedda Ruscia, Appetizer",
        "path": "bruschetta",
        "number": "1",
        "query": "Bruschetta",
        "country": "ita",
        "countryName": "Italy",
        "category": "veg-appetizer",
        "rating": 4.2
    },
    {
        "id": "10",
        "name": "Kızartma",
        "description": "Fried vegetables consisting of potatoes, chilli peppers, eggplants and zucchini served with a thick sauce",
        "src": "kizartma.jpg",
        "type": "Vegetable Dish, Side Dish",
        "path": "kizartma",
        "number": "2",
        "query": "kizartma",
        "country": "tur",
        "countryName": "Turkey",
        "category": "veg-appetizer",
        "rating": 4.1
    },
    {
        "id": "11",
        "name": "Guacamole",
        "description": "Healthy blend of mashed avocados, onions and chilli peppers topped with coriander ",
        "src": "guacamole.jpg",
        "type": "Appetizer, Spread",
        "path": "guacamole",
        "number": "3",
        "query": "guacamole",
        "country": "mex",
        "countryName": "Mexico",
        "category": "veg-appetizer",
        "rating": 4.5
    },
    {
        "id": "12",
        "name": "Onion Rings",
        "description": "Dipping onion rings in batter and deep-frying them until golden and crispy",
        "src": "onion-rings.jpg",
        "type": "Appetizer, Deep-Fried Dish",
        "path": "onion-rings",
        "number": "2",
        "query": "Onion_ring",
        "country": "usa",
        "countryName": "United States of America",
        "category": "veg-appetizer",
        "rating": 3.8
    },
    {
        "id": "13",
        "name": "Caponata",
        "description": "Delicately piquant appetizer consisting of capers, olives, onions, pine nuts, almonds, raisins and friggitello peppers, seasoned with a pinch of sugar and simmered in vinegar ",
        "src": "caponata.jpg",
        "type": "Vegetable Dish, Appetizer",
        "path": "caponata",
        "number": "2",
        "query": "Caponata",
        "country": "ita",
        "countryName": "Italy",
        "category": "veg-appetizer",
        "rating": 4.2
    },
    {
        "id": "14",
        "name": "Gazpacho",
        "src": "gazpacho.jpg",
        "description": "A cold soup consisting of crushed tomatoes, finely chopped cucumbers, onions, croutons, and vinegar",
        "type": "Vegetable Soup, Cold Soup",
        "path": "gazpacho",
        "number": "2",
        "query": "Gazpacho",
        "country": "spa",
        "countryName": "Spain",
        "category": "soup",
        "rating": 3.7
    },
    {
        "id": "15",
        "name": "Ribollita",
        "src": "ribollita.jpg",
        "description": "A fresh soup consisting of leftover bread, cannellini beans, tuscan kale, onions, carrots, and cabbage",
        "type": "Vegetable Soup, Bread Soup",
        "path": "taco-al-pastor",
        "number": "2",
        "query": "Ribollita",
        "country": "ita",
        "countryName": "Italy",
        "category": "soup",
        "rating": 4.0
    },
    {
        "id": "16",
        "name": "Houbová polévka",
        "src": "hpolev.jpg",
        "description": "Creamy mushroom soup seasoned with marjoram and cumin, served warm",
        "type": "Mushroom Soup, Mushroom Dish",
        "path": "houbova-polevka",
        "number": "2",
        "query": "houbova",
        "country": "cze",
        "countryName": "Czech Republic",
        "category": "soup",
        "rating": 4.1
    },
    {
        "id": "17",
        "name": "Lobster Bisque",
        "src": "bisque.jpg",
        "description": "Thick, creamy, rich puréed soup which includes cream, lobsters, cognac, wine, and a combination of spices",
        "type": "Seafood Soup",
        "path": "lobster-bisque",
        "number": "2",
        "query": "Bisque_(food)",
        "country": "fra",
        "countryName": "France",
        "category": "soup",
        "rating": 4.2
    },
    {
        "id": "18",
        "name": "Miso Soup",
        "src": "miso.jpg",
        "description": "Soy-based soup made from a stock called dashi, miso paste, seaweed and tofu",
        "type": "Soup, Vegan Dish",
        "path": "miso-soup",
        "number": "2",
        "query": "Miso_soup",
        "country": "jpn",
        "countryName": "Japan",
        "category": "soup",
        "rating": 4.1
    },
    {
        "id": "19",
        "name": "Borscht",
        "src": "borscht.jpg",
        "description": "Comforting soup made with fermented beetroot juice, pork, meat stock, and sautéed vegetables",
        "type": "Vegetable Soup",
        "path": "borscht",
        "number": "2",
        "query": "Borscht",
        "country": "ukr",
        "countryName": "Ukraine",
        "category": "soup",
        "rating": 4.3
    },
    {
        "id": "20",
        "name": "Pozole",
        "src": "pozole.jpg",
        "description": "Large, dried corn kernels pre-cooked in an alkaline solution with herbs, spices and chicken",
        "type": "Soup, Stew",
        "path": "pozole",
        "number": "2",
        "query": "pozole",
        "country": "mex",
        "countryName": "Mexico",
        "category": "soup",
        "rating": 4.6
    },
    {
        "id": "21",
        "name": "Clam Chowder",
        "src": "chowder.jpg",
        "description": "Creamy stew made with briny clams, chunks of salt pork, sweet onions, potatoes, and milk",
        "type": "Seafood Soup, Clam Dish",
        "path": "new-england-clam-chowder",
        "number": "2",
        "query": "Clam_chowder",
        "country": "usa",
        "countryName": "United States of America",
        "category": "soup",
        "rating": 4.2
    },
    {
        "id": "22",
        "name": "Soupe à l’oignon",
        "src": "oignon.jpg",
        "description": "Broth made with caramelized onions, meat stock, and croûtes–pieces of crispy baked bread covered with cheese",
        "type": "Onion Soup",
        "path": "soupe-a-loignon",
        "number": "2",
        "query": "French_onion_soup",
        "country": "fra",
        "countryName": "France",
        "category": "soup",
        "rating": 4.3
    },
    {
        "id": "23",
        "name": "Menestrón",
        "src": "menestron.jpg",
        "description": "Soup prepared with beef stock, beef, local vegetables such as carrots and potatoes, salsa verde made with onions, garlic, and spinach, garnished with cilantro",
        "type": "Meat Soup",
        "path": "menestron",
        "number": "2",
        "query": "Menestron",
        "country": "per",
        "countryName": "Peru",
        "category": "soup",
        "rating": 4.1
    },
    {
        "id": "24",
        "name": "Orange Chicken",
        "src": "ochicken.jpg",
        "description": "Battered chicken fried with sweet and sour orange and chilli sauce",
        "type": "Fried Chicken Dish, Deep-Fried Dish",
        "path": "orange-chicken",
        "number": "2",
        "query": "Orange_chicken",
        "country": "chn",
        "countryName": "China",
        "category": "appetizer-chicken",
        "rating": 4.2
    },
    {
        "id": "1",
        "name": "Buffalo Wings",
        "src": "bwings.jpg",
        "description": "Mouth-watering chicken wings deep-fried and served with hot sauce",
        "type": "Fried Chicken Dish, Deep-Fried Dish",
        "path": "buffalo-wings",
        "number": "1",
        "query": "Buffalo_wing",
        "country": "usa",
        "countryName": "United States of America",
        "category": "appetizer-chicken",
        "rating": 4.0
    },
    {
        "id": "25",
        "name": "Korean Fried Chicken",
        "src": "koreanfchicken.jpg",
        "description": "Battered and deep-fried chicken pieces tossed in vegetable oil and rice wine",
        "type": "Fried Chicken Dish, Deep-Fried Dish",
        "path": "korean-fried-chicken",
        "number": "1",
        "query": "Korean_fried_chicken",
        "country": "kor",
        "countryName": "South Korea",
        "category": "appetizer-chicken",
        "rating": 4.7
    },
    {
        "id": "4",
        "name": "Tandoori Chicken",
        "src": "tchicken.jpg",
        "description": "Chicken meat marinated in yogurt, seasoned with tandoori masala, nutmeg, and cumin, then cooked at high temperatures in clay ovens called tandoor",
        "type": "Chicken Dish",
        "path": "tandoori-chicken",
        "number": "2",
        "query": "Tandoori_chicken",
        "country": "ind",
        "countryName": "India",
        "category": "appetizer-chicken",
        "rating": 4.4
    },
    {
        "id": "27",
        "name": "Chicken Parmigiana",
        "src": "prmgchicken.jpg",
        "description": "Breadcrumbs-coated chicken breasts topped with tomato sauce and cheese, then baked until the cheese melts",
        "type": "Fried Chicken Dish, Breaded Cutlet",
        "path": "chicken-parmigiana",
        "number": "1",
        "query": "Chicken_parmesan",
        "country": "usa",
        "countryName": "United States of America",
        "category": "appetizer-chicken",
        "rating": 4.1
    },
    {
        "id": "28",
        "name": "Pozharsky Cutlet",
        "src": "pcutlet.jpg",
        "description": "Ground chicken breaded and fried with butter, served with roasted potatoes and green beans",
        "type": "Fried Chicken Dish",
        "path": "pozharsky-cutlet",
        "number": "1",
        "query": "Pozharsky_cutlet",
        "country": "rus",
        "countryName": "Russia",
        "category": "appetizer-chicken",
        "rating": 4.2
    },
    {
        "id": "29",
        "name": "Barberton Chicken",
        "src": "barbchicken.jpg",
        "description": "Fresh chicken pieces deep-fried until golden and crispy, served with french-fries, a vinegar based colesaw and a spicy concoction of rice, tomatoes and hot sauce",
        "type": "Fried Chicken Dish, Deep-Fried Dish",
        "path": "barberton-chicken",
        "number": "1",
        "query": "Barberton_chicken",
        "country": "srb",
        "countryName": "Serbia",
        "category": "appetizer-chicken",
        "rating": 4.5
    },
    {
        "id": "30",
        "name": "Chef's Special Fried Chicken",
        "src": "cschicken.jpg",
        "description": "Deep-fried chicken tossed with butter and served with spicy hot sauce - one of Chef’s specials ",
        "type": "Fried Chicken Dish, Deep-Fried Dish",
        "path": "chef-special-fried-chicken",
        "number": "1",
        "query": "Fried_chicken",
        "country": "usa",
        "countryName": "United States of America",
        "category": "appetizer-chicken",
        "rating": 5.0
    },
    {
        "id": "2",
        "name": "Fish 'n' Chips",
        "src": "fishchips.jpg",
        "description": "Freshly fried fish fillets and sliced fried potatoes",
        "type": "Saltwater Fish Dish, Deep-Fried Dish",
        "path": "fish-and-chips",
        "number": "2",
        "query": "Fish_and_chips",
        "country": "uk",
        "countryName": "United Kingdom",
        "category": "appetizer-fish",
        "rating": 4.0
    },
    {
        "id": "31",
        "name": "Lutefisk",
        "src": "lutefisk.jpg",
        "description": "Dried whitefish treated with lye and served with boiled potatoes, mashed green peas, melted butter and pieces of fried bacon",
        "type": "Saltwater Fish Dish",
        "path": "lutefisk",
        "number": "1",
        "query": "Lutefisk",
        "country": "nor",
        "countryName": "Norway",
        "category": "appetizer-fish",
        "rating": 2.5
    },
    {
        "id": "32",
        "name": "Grilled Sardines",
        "src": "grilledsardines.jpg",
        "description": "Fresh sardines grilled with bread, boiled potatoes and sautéed vegetables",
        "type": "Saltwater Fish Dish",
        "path": "grilled-sardines",
        "number": "1",
        "query": "Sardines_as_food",
        "country": "prt",
        "countryName": "Portugal",
        "category": "appetizer-fish",
        "rating": 4.0
    },
    {
        "id": "33",
        "name": "Saba Sushi",
        "src": "sabasushi.jpg",
        "description": "Sushi topped with marinated mackerel fillet",
        "type": "Rice Dish, Saltwater Fish Dish",
        "path": "saba-sushi",
        "number": "1",
        "query": "Sushi",
        "country": "jpn",
        "countryName": "Japan",
        "category": "appetizer-fish",
        "rating": 4.0
    },
    {
        "id": "34",
        "name": "Sole meunière",
        "src": "solemeun.jpg",
        "description": "Classic French seafood dish prepared with sole fillets breaded in plain flour and pan-fried in butter",
        "type": "Saltwater Fish Dish",
        "path": "sole-meuniere",
        "number": "1",
        "query": "Sole_meunière",
        "country": "fra",
        "countryName": "France",
        "category": "appetizer-fish",
        "rating": 4.2
    },
    {
        "id": "35",
        "name": "Baccalà Mantecato",
        "src": "baccala.jpg",
        "description": "Salted cod boiled in water and milk enriched with olive oil and garlic, served with toasted crispy bread",
        "type": "Appetizer, Saltwater Fish Dish",
        "path": "baccala-mantecato",
        "number": "1",
        "query": "Baccalà_mantecato",
        "country": "ita",
        "countryName": "Italy",
        "category": "appetizer-fish",
        "rating": 4.0
    },
    {
        "id": "36",
        "name": "Tian Bu La",
        "src": "tianbula.jpg",
        "description": "Taiwanese fish cakes made with a thick paste of whitefish fillets, eggs, potato and tapioca flour served with a brown sauce made with chilli paste, soy sauce, miso and sugar",
        "type": "Saltwater Fish Dish, Deep-Fried Fish",
        "path": "tian-bu-la",
        "number": "1",
        "query": "Taiwanese_cuisine",
        "country": "twn",
        "countryName": "Taiwan",
        "category": "appetizer-fish",
        "rating": 3.1
    },
    {
        "id": "37",
        "name": "Ryba smażona",
        "src": "ryma.jpg",
        "description": "Polish fried fish butterfy fillets served with boiled potatoes, fries, and drizzled with lemon juice ",
        "type": "Fish Dish",
        "path": "ryba-smazona",
        "number": "1",
        "query": "Ryba",
        "country": "pol",
        "countryName": "Poland",
        "category": "appetizer-fish",
        "rating": 3.8
    },
    {
        "id": "38",
        "name": "Baliq Kebab",
        "src": "baliqkebab.jpg",
        "description": "Rich fish marinated, skewered and grilled with chopped dill and lemon juice, served with sliced onions, tomatoes and lemon wedges ",
        "type": "Freshwater Fish Dish",
        "path": "baliq-kebab",
        "number": "1",
        "query": "Balyk",
        "country": "aze",
        "countryName": "Azerbaijan",
        "category": "appetizer-fish",
        "rating": 3.8
    },
    {
        "id": "39",
        "name": "Döner kebab",
        "src": "donerkebab.jpg",
        "description": "Grilled pieces of lamb shaved into a flatbread, served with vegetables and seasoned with fresh herbs and spices",
        "type": "Lamb Dish",
        "path": "doner-kebab",
        "number": "1",
        "query": "Doner_kebab",
        "country": "tur",
        "countryName": "Turkey",
        "category": "appetizer-lamb",
        "rating": 4.5
    },
    {
        "id": "40",
        "name": "Païdakia",
        "src": "paidakia.jpg",
        "description": "Lamb chops grilled on traditional charcoal barbecues paired with potatoes, lemons and creamy tzatziki sauce",
        "type": "Lamb Dish",
        "path": "paidakia",
        "number": "1",
        "query": "paidakia",
        "country": "grc",
        "countryName": "Greece",
        "category": "appetizer-lamb",
        "rating": 4.6
    },
    {
        "id": "41",
        "name": "Arrosticini",
        "src": "arrosticini.jpg",
        "description": "Sizzling hot grilled pieces of skewers with rich flavor",
        "type": "Lamb Dish",
        "path": "arrosticini",
        "number": "1",
        "query": "Arrosticini",
        "country": "ita",
        "countryName": "Italy",
        "category": "appetizer-lamb",
        "rating": 4.3
    },
    {
        "id": "42",
        "name": "Hünkar Beğendi",
        "src": "hunkar.jpg",
        "description": "Flavorful lamb stew served on top of a creamy roasted eggplant purée thickened with milk and cheese and garnished with freshly chopped parsley",
        "type": "Stew, Lamb Dish",
        "path": "hunkar-begendi",
        "number": "1",
        "query": "Hünkârbeğendi",
        "country": "tur",
        "countryName": "Turkey",
        "category": "appetizer-lamb",
        "rating": 4.5
    },
    {
        "id": "43",
        "name": "Roasted Lamb with Laver Sauce",
        "src": "lambroast.jpg",
        "description": "Roasted racks of lamb flavoured with garlic and herbs paired with a flavorful laver sauce",
        "type": "Lamb Dish",
        "path": "roasted-lamb-with-laver-sauce",
        "number": "1",
        "query": "Roast_lamb_with_laver_sauce",
        "country": "gb-wls",
        "countryName": "Wales",
        "category": "appetizer-lamb",
        "rating": 4.2
    },
    {
        "id": "44",
        "name": "Sosatie",
        "src": "sosatie.jpg",
        "description": "Pieces of lamb marinated in a sauce made with onions, garlic, hot peppers and tamarind juice, and skewered and barbecued with apricots and mushrooms",
        "type": "Lamb Dish",
        "path": "sosatie",
        "number": "1",
        "query": "Sosatie",
        "country": "rsa",
        "countryName": "South Africa",
        "category": "appetizer-lamb",
        "rating": 4.1
    },
    {
        "id": "45",
        "name": "Fried Lamb Ribs",
        "src": "lambribs.jpg",
        "description": "Lamb ribs fried in ginger, cloves, turmeric and oil",
        "type": "Lamb Dish",
        "path": "fried-lamb-ribs",
        "number": "1",
        "query": "Wazwan",
        "country": "ind",
        "countryName": "India",
        "category": "appetizer-lamb",
        "rating": 4.4
    },
    {
        "id": "46",
        "name": "Colonial Goose",
        "src": "cngoose.jpg",
        "description": "Mutton leg deboned and stuffed with a mixture of honey, dried apricots, breadcrumbs and onions, seasoned with parsley and served with pumpkins and potatoes",
        "type": "Lamb Dish, Mutton Dish",
        "path": "colonial-goose",
        "number": "1",
        "query": "Colonial_goose",
        "country": "nzl",
        "countryName": "New Zealand",
        "category": "appetizer-lamb",
        "rating": 4.6
    },
    {
        "id": "47",
        "name": "Crab Cake",
        "src": "crabcake.jpg",
        "description": "Minced crab meat flavored with mustard, Worcestershire sauce, and fresh herbs",
        "type": "Crab Dish",
        "path": "crab-cake",
        "number": "1",
        "query": "Crab_cake",
        "country": "usa",
        "countryName": "United States of America",
        "category": "appetizer-seafood",
        "rating": 4.1
    },
    {
        "id": "48",
        "name": "Fried Clams",
        "src": "friedclams.jpg",
        "description": "Whole soft-shell clams dipped in milk and cornflour, then deepfried until golden",
        "type": "Clam Dish, Deep-Fried Dish",
        "path": "fried-clams",
        "number": "1",
        "query": "Fried_clams",
        "country": "usa",
        "countryName": "United States of America",
        "category": "appetizer-seafood",
        "rating": 3.9
    },
    {
        "id": "49",
        "name": "Takoyaki",
        "src": "takoyaki.jpg",
        "description": "Diced octopus pieces grilled in soy sauce enriched egg batter seasoned with sliced scallions, pickled ginger and dried fish flakes",
        "type": "Octopus Dish",
        "path": "takoyaki",
        "number": "1",
        "query": "Takoyaki",
        "country": "jpn",
        "countryName": "Japan",
        "category": "appetizer-seafood",
        "rating": 4.3
    },
    {
        "id": "3",
        "name": "Lobster Roll",
        "src": "lobsterroll.jpg",
        "description": "Cooked lobster meat drizzled with melted butter and placed into hotdog rolls along with lettuce and lemon juice",
        "type": "Sandwich, Lobster Dish",
        "path": "lobster-roll",
        "number": "3",
        "query": "Lobster_roll",
        "country": "usa",
        "countryName": "United States of America",
        "category": "appetizer-seafood",
        "rating": 4.4
    },
    {
        "id": "50",
        "name": "Ebi Furai",
        "src": "ebifurai.jpg",
        "description": "Black tiger shrimps dipped in egg wash, coated in panko breadcrumbs, then deep-fried ",
        "type": "Shrimp Dish, Deep-Fried Dish",
        "path": "ebi-furai",
        "number": "1",
        "query": "Furai",
        "country": "jpn",
        "countryName": "Japan",
        "category": "appetizer-seafood",
        "rating": 4.4
    },
    {
        "id": "51",
        "name": "Oysters Rockefeller",
        "src": "oysterock.jpg",
        "description": "Baked oysters served on half shells topped with butter sauce, breadcrumbs and parsley ",
        "type": "Oyster Dish, Appetizer",
        "path": "oysters-rockefeller",
        "number": "1",
        "query": "Oysters_Rockefeller",
        "country": "usa",
        "countryName": "United States of America",
        "category": "appetizer-seafood",
        "rating": 4.0
    },
    {
        "id": "52",
        "name": "Escargot",
        "src": "escargot.jpg",
        "description": "Fresh snails cooked with garlic butter, chicken stock and wine, placed in shells and served with garlic and thyme",
        "type": "Snail Dish, Appetizer",
        "path": "escargot",
        "number": "1",
        "query": "Escargot",
        "country": "fra",
        "countryName": "France",
        "category": "appetizer-seafood",
        "rating": 3.6
    },
    {
        "id": "53",
        "name": "Salt and Pepper Calamari",
        "src": "calamari.jpg",
        "description": "Bite-sized pieces of squid mixed with Shaoxing wine, dredged in flour and deep-fried in garlic oil until golden",
        "type": "Snail Dish, Appetizer",
        "path": "salt-and-pepper-calamari",
        "number": "1",
        "query": "Squid_as_food",
        "country": "aus",
        "countryName": "Australia",
        "category": "appetizer-seafood",
        "rating": 4.4
    },
    {
        "id": "54",
        "name": "Frittata",
        "src": "frittata.jpg",
        "description": "Whisked eggs fried in a mixture of butter and oil with prosciutto, grated cheese and sautéed onions",
        "type": "Egg Dish, Appetizer",
        "path": "frittata",
        "number": "1",
        "query": "Frittata",
        "country": "ita",
        "countryName": "Italy",
        "category": "appetizer-breakfastnonveg",
        "rating": 3.7
    },
    {
        "id": "55",
        "name": "Huevos rancheros",
        "src": "huevo.jpg",
        "description": "Egg tortilla consisting of beans and meats, covered with tomato-chili-sauce, avocado slices and garlic-chile-sauce",
        "type": "Egg Dish, Breakfast",
        "path": "huevos-rancheros",
        "number": "1",
        "query": "Huevos_rancheros",
        "country": "mex",
        "countryName": "Mexico",
        "category": "appetizer-breakfastnonveg",
        "rating": 4.1
    },
    {
        "id": "56",
        "name": "Shakshouka",
        "src": "shakshouka.jpg",
        "description": "Eggs poached in a spicy tomato sauce with salty feta cheese on top, served sizzling hot",
        "type": "Egg Dish, Breakfast",
        "path": "shakshouka",
        "number": "1",
        "query": "Shakshouka",
        "country": "tun",
        "countryName": "Tunisia",
        "category": "appetizer-breakfastnonveg",
        "rating": 4.3
    },
    {
        "id": "57",
        "name": "Eggs Benedict",
        "src": "eggsbenedict.jpg",
        "description": "Toasted halves of an English muffin topped with a slice of ham, bacon, poached eggs and sauce Hollandaise",
        "type": "Egg Dish, Breakfast",
        "path": "eggs-benedict",
        "number": "1",
        "query": "Eggs_Benedict",
        "country": "usa",
        "countryName": "United States of America",
        "category": "appetizer-breakfastnonveg",
        "rating": 4.3
    },
    {
        "id": "58",
        "name": "Burek",
        "src": "burek.jpg",
        "description": "Layers of phyllo dough stuffed with savory fillings such as ground beef, onions, spinaches and potatoes",
        "type": "Breakfast, Phyllo Pastry",
        "path": "burek",
        "number": "1",
        "query": "Börek",
        "country": "bih",
        "countryName": "Bosnia and Herzegovina",
        "category": "appetizer-breakfastnonveg",
        "rating": 4.3
    },
    {
        "id": "59",
        "name": "Sfiha",
        "src": "sfiha.jpg",
        "description": "Open-faced meat pie consisting of minced lamb, chopped onions and tomatoes, spices, olive oil and yoghurt ",
        "type": "Savory Pie, Breakfast",
        "path": "sfiha",
        "number": "1",
        "query": "Sfiha",
        "country": "lbn",
        "countryName": "Lebanon",
        "category": "appetizer-breakfastnonveg",
        "rating": 4.4
    },
    {
        "id": "60",
        "name": "Weißwürste",
        "src": "weisswurste.jpg",
        "description": "White sausages consisting of a mixture of pork, veal and pork fat, seasoned with parsley, pepper and lemon, served hot with pretzels",
        "type": "White Sausage, Breakfast",
        "path": "weisswurste",
        "number": "1",
        "query": "Weisswurst",
        "country": "deu",
        "countryName": "Germany",
        "category": "appetizer-breakfastnonveg",
        "rating": 3.8
    },
    {
        "id": "61",
        "name": "Breakfast Burrito",
        "src": "breburrito.jpg",
        "description": "Tortilla stuffed with eggs, bacons, potatoes, tomatoes, cheese, ham, spinach and beans, served with nachos",
        "type": "Breakfast",
        "path": "breakfast-burrito",
        "number": "1",
        "query": "Breakfast_burrito",
        "country": "usa",
        "countryName": "United States of America",
        "category": "appetizer-breakfastnonveg",
        "rating": 3.9
    },
    {
        "id": "62",
        "name": "Croissant",
        "src": "croissant.jpg",
        "description": "Flaky golden-coloured, crescent-shaped pastries made with pure butter and a slightly sweet yeast dough",
        "type": "Sweet Pastry, Breakfast",
        "path": "croissant",
        "number": "1",
        "query": "Croissant",
        "country": "fra",
        "countryName": "France",
        "category": "appetizer-breakfastveg",
        "rating": 4.5
    },
    {
        "id": "63",
        "name": "Arepa",
        "src": "arepa.jpg",
        "description": "Crispy brown corn bread stuffed with beans, cheese and avocado",
        "type": "Sandwich Type, Breakfast, Flatbread",
        "path": "arepa",
        "number": "1",
        "query": "Arepa",
        "country": "col",
        "countryName": "Colombia",
        "category": "appetizer-breakfastveg",
        "rating": 4.2
    },
    {
        "id": "64",
        "name": "Börek",
        "src": "borek.jpg",
        "description": "Baked dish consisting of a savory sweet filling wrapped in thinly stretched sheets of dough made with flour and salt",
        "type": "Phyllo Pastry, Breakfast",
        "path": "borek",
        "number": "1",
        "query": "Börek",
        "country": "tur",
        "countryName": "Turkey",
        "category": "appetizer-breakfastveg",
        "rating": 4.3
    },
    {
        "id": "65",
        "name": "Churros",
        "src": "churros.jpg",
        "description": "Elongated, crispy, crunchy and intensely fragrant deep-fried yeast dough encrusted with cinnamon sugar",
        "type": "Sweet Pastry, Breakfast",
        "path": "churros",
        "number": "1",
        "query": "Churros",
        "country": "spa",
        "countryName": "Spain",
        "category": "appetizer-breakfastveg",
        "rating": 4.1
    },
    {
        "id": "65",
        "name": "Medialunas",
        "src": "medialunas.jpg",
        "description": "Soft and moist crescent rolls made with butter",
        "type": "Sweet Pastry, Breakfast, Viennoiserie",
        "path": "medialunas",
        "number": "1",
        "query": "Croissant",
        "country": "arg",
        "countryName": "Argentina",
        "category": "appetizer-breakfastveg",
        "rating": 4.2
    },
    {
        "id": "66",
        "name": "Idli",
        "src": "idli.jpg",
        "description": "Savory Indian cake made with a batter consisting of fermented lentils and rice, which is then steamed",
        "type": "Breakfast",
        "path": "idli",
        "number": "1",
        "query": "Idli",
        "country": "ind",
        "countryName": "India",
        "category": "appetizer-breakfastveg",
        "rating": 3.8
    },
    {
        "id": "67",
        "name": "Syrniki",
        "src": "syrniki.jpg",
        "description": "Fried cottage cheese pancakes (eggless) that are garnished with honey, sour cream and apple sauce",
        "type": "Breakfast, Cheese Dish",
        "path": "syrniki",
        "number": "1",
        "query": "Syrniki",
        "country": "rus",
        "countryName": "Russia",
        "category": "appetizer-breakfastveg",
        "rating": 4.4
    },
    {
        "id": "68",
        "name": "Home Fries",
        "src": "hfries.jpg",
        "description": "Fried chunks of potatoes in butter and oil until crispy and golden",
        "type": "Breakfast, Potato Dish",
        "path": "home-fries",
        "number": "1",
        "query": "Home_fries",
        "country": "usa",
        "countryName": "United States of America",
        "category": "appetizer-breakfastveg",
        "rating": 3.8
    },
    {
        "id": "69",
        "name": "Nachos",
        "src": "nachos.jpg",
        "description": "Plate of tortilla chips, melted cheese, and jalapeños topped with corn, lettuce, onions, tomatoes and meat",
        "type": "Snack",
        "path": "nachos",
        "number": "1",
        "query": "Nachos",
        "country": "mex",
        "countryName": "Mexico",
        "category": "snacks",
        "rating": 4.1
    },
    {
        "id": "70",
        "name": "Spring Rolls",
        "src": "srolls.jpg",
        "description": "Thin sheets of dough filled with various ingredients",
        "type": "Snack, Deep-Fried Dish",
        "path": "spring-rolls",
        "number": "1",
        "query": "Spring_roll",
        "country": "chn",
        "countryName": "China",
        "category": "snacks",
        "rating": 4.1
    },
    {
        "id": "71",
        "name": "Falafel",
        "src": "falafel.jpg",
        "description": "Protein-packed chickpea fritters flavoured with parsley, coriander, cumin and onions",
        "type": "Snack, Vegan Dish",
        "path": "falafel",
        "number": "1",
        "query": "Falafel",
        "country": "isr",
        "countryName": "Israel",
        "category": "snacks",
        "rating": 4.1
    },
    {
        "id": "72",
        "name": "Poutine",
        "src": "poutine.jpg",
        "description": "French fries drowned in a thick brown gravy dotted with clumps of pale, soft, semi-creamy cheese curds",
        "type": "Potato Dish, Snack, Cheese Dish",
        "path": "poutine",
        "number": "1",
        "query": "Poutine",
        "country": "can",
        "countryName": "Canada",
        "category": "snacks",
        "rating": 4.2
    },
    {
        "id": "73",
        "name": "Bánh xèo",
        "src": "banhxeo.jpg",
        "description": "Sizzling pancakes made with rice flour, combined with water, turmeric and coconut cream",
        "type": "Pancake, Snack",
        "path": "banh-xeo",
        "number": "1",
        "query": "Bánh_xèo",
        "country": "vnm",
        "countryName": "Vietnam",
        "category": "snacks",
        "rating": 4.2
    },
    {
        "id": "74",
        "name": "Shawarma",
        "src": "shawarma.jpg",
        "description": "Marinated meat flavored with dried lime, spicy paprika, garlic, ginger, and lemon tucked inside a warm flatbread",
        "type": "Sandwich, Snack",
        "path": "shawarma",
        "number": "1",
        "query": "Shawarma",
        "country": "sau",
        "countryName": "Saudi Arabia",
        "category": "snacks",
        "rating": 4.5
    },
    {
        "id": "75",
        "name": "Pizzette",
        "src": "pizzette.jpg",
        "description": "Small version of pizza topped with sauces, cheeses and various other ingredients",
        "type": "Pizza, Snack",
        "path": "pizzette",
        "number": "1",
        "query": "Pizzetta",
        "country": "ita",
        "countryName": "Italy",
        "category": "snacks",
        "rating": 4.4
    },
    {
        "id": "76",
        "name": "Corn on the Cob",
        "src": "corncob.jpg",
        "description": "Roasted sweet corn seasoned with salt and smeared with butter",
        "type": "Snack",
        "path": "corn-on-the-cob",
        "number": "1",
        "query": "Corn_on_the_cob",
        "country": "usa",
        "countryName": "United States of America",
        "category": "snacks",
        "rating": 4.0
    },
    {
        "id": "77",
        "name": "Biryani",
        "src": "biryani.jpg",
        "description": "Basmati rice cooked with meat, potatoes, eggs, yogurt, onions, and saffron",
        "type": "Rice Dish",
        "path": "biryani",
        "number": "1",
        "query": "Biryani",
        "country": "ind",
        "countryName": "India",
        "category": "maincourse-rice",
        "rating": 4.2
    },
    {
        "id": "78",
        "name": "Fried Rice",
        "src": "friedrice.jpg",
        "description": "Rice dish consisting of eggs, vegetables, meat, and shrimps, flavored with soy sauce",
        "type": "Rice Dish",
        "path": "fried-rice",
        "number": "1",
        "query": "Fried_rice",
        "country": "chn",
        "countryName": "China",
        "category": "maincourse-rice",
        "rating": 4.4
    },
    {
        "id": "6",
        "name": "Seafood Paella",
        "src": "paella.jpg",
        "description": "Saffron-flavored rice which includes meat, seafood, and vegetables with a crispy bottom layer",
        "type": "Rice Dish, Seafood",
        "path": "seafood-paella",
        "number": "2",
        "query": "Paella",
        "country": "spa",
        "countryName": "Spain",
        "category": "maincourse-rice",
        "rating": 4.3
    },
    {
        "id": "79",
        "name": "Nasi Goreng",
        "src": "nasigoreng.jpg",
        "description": "Pre-cooked rice fried in oil, spiced up with shallots, garlic, chili, and ginger, flavored with sweet soy sauce",
        "type": "Rice Dish",
        "path": "nasi-goreng",
        "number": "1",
        "query": "Nasi_goreng",
        "country": "idn",
        "countryName": "Indonesia",
        "category": "maincourse-rice",
        "rating": 4.3
    },
    {
        "id": "80",
        "name": "Nasi Lemak",
        "src": "nasilemak.jpg",
        "description": "Rice cooked in coconut milk served with anchovies, cucumbers, peanuts, and boiled eggs, spiced up with a chili paste called sambal",
        "type": "Rice Dish",
        "path": "nasi-lemak",
        "number": "1",
        "query": "Nasi_lemak",
        "country": "mys",
        "countryName": "Malaysia",
        "category": "maincourse-rice",
        "rating": 4.2
    },
    {
        "id": "81",
        "name": "Mandi",
        "src": "mandi.jpg",
        "description": "Fragrant basmati rice cooked with lamb or chicken in the tandoor, accompanied with spicy tomato chutneys",
        "type": "Meat Dish, Rice Dish",
        "path": "mandi",
        "number": "1",
        "query": "Mandi_(food)",
        "country": "yem",
        "countryName": "Yemen",
        "category": "maincourse-rice",
        "rating": 3.7
    },
    {
        "id": "82",
        "name": "Duck Rice",
        "src": "duckrice.jpg",
        "description": "Rice served with roasted duck, doused in a thick soy-based sauce, accompanied by tofu, vegetables and hard-boiled eggs",
        "type": "Duck Dish, Rice Dish",
        "path": "duck-rice",
        "number": "1",
        "query": "Duck_rice",
        "country": "sgp",
        "countryName": "Singapore",
        "category": "maincourse-rice",
        "rating": 4.1
    },
    {
        "id": "83",
        "name": "Galinhada",
        "src": "galinhada.jpg",
        "description": "Brazilian stew made with rice and chicken, served with hot sauce and garnished with finely diced green onions",
        "type": "Stew, Rice Dish, Chicken Dish",
        "path": "galinhada",
        "number": "1",
        "query": "Galinhada",
        "country": "bra",
        "countryName": "Brazil",
        "category": "maincourse-rice",
        "rating": 3.9
    },
    {
        "id": "84",
        "name": "Panta Ilish",
        "src": "pantailish.jpg",
        "description": "Soaked rice served with fried ilish fish, onions, tomatoes, fresh chili peppers, generously seasoned with turmeric, chili powder and other spices",
        "type": "Rice Dish, Freshwater Fish Dish",
        "path": "panta-ilish",
        "number": "1",
        "query": "Panta_bhat",
        "country": "bgd",
        "countryName": "Bangladesh",
        "category": "maincourse-rice",
        "rating": 4.2
    },
    {
        "id": "85",
        "name": "Jollof rice",
        "src": "jollofrice.jpg",
        "description": "Rice cooked in a rich tomato sauce with chicken, onions, coconut milk, nutmeg, and partminger",
        "type": "Rice Dish",
        "path": "jollof-rice",
        "number": "1",
        "query": "Jollof_rice",
        "country": "nga",
        "countryName": "Nigeria",
        "category": "maincourse-rice",
        "rating": 4.3
    },
    {
        "id": "86",
        "name": "Khao Phat",
        "src": "khaophat.jpg",
        "description": "Stir-fried jasmine rice with onions, garlic, fish sauce, thin soy sauce, scrambled eggs, drizzled with fresh lime juice",
        "type": "Rice Dish",
        "path": "khao-phat",
        "number": "1",
        "query": "Thai_fried_rice",
        "country": "tha",
        "countryName": "Thailand",
        "category": "maincourse-rice",
        "rating": 4.3
    },
    {
        "id": "87",
        "name": "Uzbek Plov",
        "src": "plov.jpg",
        "description": "Rice added in a layer of sautéed meat, carrots, and onions, topped with water and simmered until the rice is full cooked",
        "type": "Rice Dish",
        "path": "uzbek-plov",
        "number": "1",
        "query": "Pilaf",
        "country": "uzb",
        "countryName": "Uzbekistan",
        "category": "maincourse-rice",
        "rating": 4.1
    },
    {
        "id": "88",
        "name": "Mussel with Rice",
        "src": "musselrice.jpg",
        "description": "Rice combined with mussels and onions, carrots and bell peppers chopped and sautéed in butter",
        "type": "Rice Dish, Mussel Dish",
        "path": "mussel-with-rice",
        "number": "1",
        "query": "Chilean_cuisine",
        "country": "chl",
        "countryName": "Chile",
        "category": "maincourse-rice",
        "rating": 3.6
    },
    {
        "id": "89",
        "name": "Risotto ai Funghi",
        "src": "mushrisotto.jpg",
        "description": "Sautéed Carnaroli rice in butter with mushrooms, parmesan cheese, finely chopped onions, and shallots",
        "type": "Rice Dish, Mushroom Dish",
        "path": "risotto-ai-funghi",
        "number": "1",
        "query": "Risotto",
        "country": "ita",
        "countryName": "Italy",
        "category": "maincourse-rice",
        "rating": 4.2
    },
    {
        "id": "90",
        "name": "Kimchi Bokkeumbap",
        "src": "kimchibap.jpg",
        "description": "Combination of fried rice and kimchi, topped with a fried egg and garnished with sesame seeds and green onions",
        "type": "Rice Dish, Vegetable Dish",
        "path": "kimchi-bokkeumbap",
        "number": "1",
        "query": "Kimchi_fried_rice",
        "country": "kor",
        "countryName": "South Korea",
        "category": "maincourse-rice",
        "rating": 4.2
    },
    {
        "id": "91",
        "name": "Arroz Chaufa",
        "src": "arrozchaufa.jpg",
        "description": "Rice fried with shredded chicken, salami, garlic, ginger, slivered almonds, eggs, chicken stock, soy sauce, and pineapple chunks",
        "type": "Rice Dish, Stir-Fry",
        "path": "arroz-chaufa",
        "number": "1",
        "query": "Arroz_chaufa",
        "country": "per",
        "countryName": "Peru",
        "category": "maincourse-rice",
        "rating": 4.3
    },
]

export default foodData;