const foodData = [
    {
        "id": "1",
        "name": "Buffalo Wings",
        "src": "bwings.jpg",
        "type": "Fried Chicken Dish, Deep-Fried Dish",
        "path": "buffalo-wings",
        "number": "1",
        "query": "Buffalo_wing",
        "country": "usa",
        "countryName": "United States of America",
        "category": "appetizer-chicken",
        "price": 115.90,
        "rating": 4.0
    },
    {
        "id": "2",
        "name": "Fish 'n' Chips",
        "src": "fishchips.jpg",
        "type": "Saltwater Fish Dish, Deep-Fried Dish",
        "path": "fish-and-chips",
        "number": "2",
        "query": "Fish_and_chips",
        "country": "uk",
        "countryName": "United Kingdom",
        "category": "appetizer-fish",
        "price": 100,
        "rating": 4.0
    },
    {
        "id": "3",
        "name": "Lobster Roll",
        "src": "lobsterroll.jpg",
        "type": "Sandwich, Lobster Dish",
        "path": "lobster-roll",
        "number": "3",
        "query": "Lobster_roll",
        "country": "usa",
        "countryName": "United States of America",
        "category": "appetizer-seafood",
        "price": 167.44,
        "rating": 4.4
    },
    {
        "id": "4",
        "name": "Tandoori Chicken",
        "src": "tchicken.jpg",
        "type": "Chicken Dish",
        "path": "tandoori-chicken",
        "number": "2",
        "query": "Tandoori_chicken",
        "country": "ind",
        "countryName": "India",
        "category": "appetizer-chicken",
        "price": 200.29,
        "rating": 4.4
    },
    {
        "id": "5",
        "name": "Shish Kebab",
        "src": "kebab.jpg",
        "type": "Meat Dish",
        "path": "shish-kebab",
        "number": "2",
        "query": "Shish_kebab",
        "country": "tur",
        "countryName": "Turkey",
        "rating": 4.5
    },
    {
        "id": "6",
        "name": "Seafood Paella",
        "src": "paella.jpg",
        "type": "Rice Dish, Seafood",
        "path": "seafood-paella",
        "number": "2",
        "query": "Paella",
        "country": "spa",
        "countryName": "Spain",
        "category": "maincourse-rice",
        "price": 329.37,
        "rating": 4.3
    },
    {
        "id": "7",
        "name": "Tacos al Pastor",
        "src": "taco.jpg",
        "type": "Pork Dish",
        "path": "taco-al-pastor",
        "number": "2",
        "query": "Al_pastor",
        "country": "mex",
        "countryName": "Mexico",
        "rating": 4.6
    },
    {
        "id": "8",
        "name": "Churrasco",
        "src": "churrasco.jpg",
        "type": "Barbecue, Technique",
        "path": "churrasco",
        "number": "2",
        "query": "Churrasco",
        "country": "bra",
        "countryName": "Brazil",
        "rating": 4.6
    }
]

export default foodData;